---
- name: Malware Containment
  hosts: all
  gather_facts: yes
  tasks:
    - name: Kill malicious process
      win_shell: |
        taskkill /F /IM "{{ malware_process_name }}"
      when: malware_process_name is defined

    - name: Remove malicious file
      win_file:
        path: "{{ malware_file_path }}"
        state: absent
      when: malware_file_path is defined

    - name: Optional - Trigger Windows Defender Scan
      win_shell: |
        Start-MpScan -ScanType Full
