- name: Malware Containment
  hosts: all
  gather_facts: yes
  vars:
    # Example: set per host/group vars in AWX
    malware_process_name: "badprocess.exe"
    malware_file_path: "C:\\malware\\badfile.exe"

  tasks:

    - name: Kill malicious process
      win_shell: |
        taskkill /F /IM "{{ malware_process_name }}"
      when: malware_process_name is defined
      ignore_errors: yes

    - name: Remove malicious file
      win_file:
        path: "{{ malware_file_path }}"
        state: absent
      when: malware_file_path is defined
      ignore_errors: yes

    - name: Check installed antivirus products
      win_shell: |
        Get-CimInstance -Namespace root\SecurityCenter2 -ClassName AntiVirusProduct |
          Select-Object -ExpandProperty displayName
      register: av_list

    - name: Trigger Checkpoint scan if installed
      win_shell: |
        "C:\Program Files (x86)\CheckPoint\Endpoint Security\Threat Emulation\WscHelper.exe" /scan /full
      when: "'Checkpoint' in av_list.stdout"
      ignore_errors: yes

    - name: Trigger Windows Defender scan if no third-party AV
      win_shell: Start-MpScan -ScanType Full
      when: "'Checkpoint' not in av_list.stdout"
      ignore_errors: yes

