- name: Apply Windows SCA Hardening
  hosts: all
  gather_facts: yes
  tasks:

    - name: Disable SMBv1
      win_feature:
        name: FS-SMB1
        state: absent

    - name: Enable Windows Firewall for all profiles
      win_shell: |
        Set-NetFirewallProfile -Profile Domain,Private,Public -Enabled True
      args:
        executable: powershell
      register: firewall_result

    - name: Verify Windows Firewall status
      win_shell: |
        Get-NetFirewallProfile | Select-Object Name,Enabled
      args:
        executable: powershell
      register: firewall_status

    - name: Enforce password complexity for Administrator
      win_password_policy:
        complexity: yes
        minimum_length: 14
        history_size: 24

